import type { TemplateProject, VideoProject } from "./schema";

export function createDefaultProject(): TemplateProject {
  const now = new Date().toISOString();
  const layerDefaults = {
    is3D: false,
    transform3D: {
      position: [0, 0, 1] as [number, number, number],
      rotation: [0, 0, 0] as [number, number, number],
      scale: 1,
    },
    transform2D: {
      x: 120,
      y: 110,
      width: 420,
      height: 120,
      rotation: 0,
      opacity: 1,
    },
    textStyle: {
      fontFamily: "Inter",
      fontWeight: 700,
      fontSize: 48,
      color: "#152144",
      align: "left" as const,
      lineHeight: 1.05,
      letterSpacing: -1,
    },
    textAnimation: {
      entrance: "none" as const,
      exit: "none" as const,
      durationInFrames: 18,
      typingSpeed: 18,
      cursor: "line" as const,
    },
  };
  return {
    schemaVersion: 2,
    id: crypto.randomUUID(),
    name: "Untitled Device Template",
    canvas: { width: 1280, height: 720, fps: 30, durationInFrames: 450 },
    model: {
      fileName: "Untitled.glb",
      position: [0, 0, 0],
      rotation: [-15, 25, 0],
      scale: 1,
      pivot: [0, 0, 0],
      frontAxis: "+Z",
      defaultTransform: {
        position: [0, 0, 0],
        rotation: [-15, 25, 0],
        scale: 1,
        pivot: [0, 0, 0],
        frontAxis: "+Z",
      },
    },
    camera: {
      position: [0, 0.6, 4],
      target: [0, 0, 0],
      fov: 35,
      defaultPosition: [0, 0.6, 4],
      defaultTarget: [0, 0, 0],
    },
    lighting: {
      preset: "Soft Studio",
      environmentIntensity: 1.2,
      keyColor: "#ffffff",
      keyIntensity: 2.4,
      keyPosition: [3, 5, 4],
      fillIntensity: 1.2,
      shadowOpacity: 0.3,
      shadowSoftness: 2.5,
    },
    screen: {
      mode: "material",
      materialName: "17ProMax_Screen",
      testPattern: false,
      fit: "fill",
      flipY: false,
      rotation: 0,
      offset: [0, 0],
      scale: [1, 1],
      emissionIntensity: 1,
      planePosition: [0, 1, 0.02],
      planeRotation: [0, 0, 0],
      planeSize: [0.9, 1.8],
    },
    background: {
      preset: "Lilac Glow",
      type: "gradient",
      colorA: "#d9e8ff",
      colorB: "#f0d9ec",
      angle: 135,
    },
    layers: [
      {
        ...layerDefaults,
        id: "camera",
        type: "camera",
        name: "Camera",
        startFrame: 0,
        durationInFrames: 450,
        visible: true,
        locked: true,
        replaceable: false,
        zIndex: 0,
        color: "#9dc6ff",
      },
      {
        ...layerDefaults,
        id: "lighting",
        type: "lighting",
        name: "Lighting",
        startFrame: 0,
        durationInFrames: 450,
        visible: true,
        locked: true,
        replaceable: false,
        zIndex: 0,
        color: "#ffd38f",
      },
      {
        ...layerDefaults,
        id: "phone",
        type: "device",
        name: "Pro Phone",
        startFrame: 0,
        durationInFrames: 450,
        visible: true,
        locked: false,
        replaceable: false,
        zIndex: 1,
        color: "#b9a9ff",
      },
      {
        ...layerDefaults,
        id: "media",
        type: "screen-media",
        name: "Screen Media",
        startFrame: 0,
        durationInFrames: 450,
        visible: true,
        locked: false,
        replaceable: true,
        zIndex: 2,
        color: "#8fbdfd",
      },
      {
        ...layerDefaults,
        id: "title",
        type: "text",
        name: "Title",
        startFrame: 16,
        durationInFrames: 177,
        visible: true,
        locked: false,
        replaceable: true,
        zIndex: 3,
        color: "#c0aaff",
        content: "Your app. Beautifully launched.",
      },
      {
        ...layerDefaults,
        id: "background",
        type: "background",
        name: "Background",
        startFrame: 0,
        durationInFrames: 450,
        visible: true,
        locked: false,
        replaceable: true,
        zIndex: -1,
        color: "#b9c4d3",
      },
    ],
    keyframeTracks: [],
    createdAt: now,
    updatedAt: now,
  };
}

export function createDefaultVideoProject(): VideoProject {
  const composition = createDefaultProject(),
    sceneId = crypto.randomUUID();
  return {
    schemaVersion: 3,
    id: composition.id,
    name: composition.name,
    canvas: { width: 1280, height: 720, fps: 30 },
    scenes: [
      {
        id: sceneId,
        name: "Scene 1",
        order: 0,
        sourceStartFrame: 0,
        durationInFrames: composition.canvas.durationInFrames,
        transitionToNext: { type: "cut", durationInFrames: 15 },
        composition,
        createdAt: composition.createdAt,
        updatedAt: composition.updatedAt,
      },
    ],
    activeSceneId: sceneId,
    audioTracks: [
      {
        id: "music",
        name: "Music",
        type: "music",
        muted: false,
        volume: 1,
        clips: [],
      },
      {
        id: "voiceover",
        name: "Voice-over",
        type: "voiceover",
        muted: false,
        volume: 1,
        clips: [],
      },
      {
        id: "sfx",
        name: "Sound Effects",
        type: "sfx",
        muted: false,
        volume: 1,
        clips: [],
      },
    ],
    globalOverlays: [],
    createdAt: composition.createdAt,
    updatedAt: composition.updatedAt,
  };
}
