import {useMemo, useState, type ReactNode} from 'react';
import * as I from 'lucide-react';
import type {LucideIcon} from 'lucide-react';
import {easeOutCubic, formatTimecode} from '../animation/frame';
import type {ProjectLayer, TemplateProject} from '../project/schema';
import {useEditorStore} from '../store/editorStore';
import type {TransformMode} from '../store/editorStore';
import {useEditorRuntime} from '../store/useEditorRuntime';
import {inspectGlb} from '../model/inspectGlb';
import {saveAsset} from '../persistence/database';
import {SceneCanvas} from '../scene/SceneCanvas';

const icons: Record<ProjectLayer['type'], LucideIcon> = {camera:I.Video,lighting:I.Sun,device:I.Smartphone,'screen-media':I.Image,text:I.Type,image:I.Image,background:I.PanelTop};
const bgClass=(name:string)=>`bg-${name.replace(/ /g,'-').toLowerCase()}`;

export function App(){
 useEditorRuntime();
 const project=useEditorStore(s=>s.project), frame=useEditorStore(s=>s.currentFrame), playing=useEditorStore(s=>s.playing), selectedId=useEditorStore(s=>s.selectedLayerId), tool=useEditorStore(s=>s.activeTool), zoom=useEditorStore(s=>s.zoom), preview=useEditorStore(s=>s.preview), status=useEditorStore(s=>s.saveStatus), past=useEditorStore(s=>s.past), future=useEditorStore(s=>s.future);
 const update=useEditorStore(s=>s.updateProject), setFrame=useEditorStore(s=>s.setFrame), setPlaying=useEditorStore(s=>s.setPlaying), setSelected=useEditorStore(s=>s.setSelectedLayer), setTool=useEditorStore(s=>s.setActiveTool), setZoom=useEditorStore(s=>s.setZoom), setPreview=useEditorStore(s=>s.setPreview), undo=useEditorStore(s=>s.undo), redo=useEditorStore(s=>s.redo), persist=useEditorStore(s=>s.persist);
 const selected=project.layers.find(layer=>layer.id===selectedId)??project.layers[0];
 const transformMode=useEditorStore(s=>s.transformMode),setTransformMode=useEditorStore(s=>s.setTransformMode);
 const [uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('');
 const [frameRequest,setFrameRequest]=useState(0);
 const replaceModel=async(file?:File)=>{
  if(!file)return;
  setUploading(true);setUploadError('');
  try{
   const stats=await inspectGlb(file),assetId=await saveAsset(file);
   update(d=>{d.model={assetId,fileName:file.name,fileSize:file.size,stats,position:[0,0,0],rotation:[0,0,0],scale:1,pivot:[0,0,0],frontAxis:'+Z',defaultTransform:{position:[0,0,0],rotation:[0,0,0],scale:1,pivot:[0,0,0],frontAxis:'+Z'}};d.screen=null});
  }catch(error){setUploadError(error instanceof Error?error.message:'The model could not be loaded.')}finally{setUploading(false)}
 };
 if(preview)return <Preview project={project} frame={frame} playing={playing} onFrame={setFrame} onPlay={setPlaying} onClose={()=>setPreview(false)}/>;
 return <main>
  <header><button className="icon" aria-label="Back"><I.ChevronLeft/></button><div className="project"><input aria-label="Project name" value={project.name} onChange={e=>update(d=>{d.name=e.target.value||'Untitled Template'})}/><span className={status==='saved'?'saved':'saving'}/><small>{status==='error'?'Save failed':status==='saved'?'Saved':status==='saving'?'Saving…':'Unsaved'}</small></div><div className="history"><button aria-label="Undo" disabled={!past.length} onClick={undo}><I.Undo2/></button><button aria-label="Redo" disabled={!future.length} onClick={redo}><I.Redo2/></button></div><button className="ratio">16:9 <I.ChevronDown/></button><div className="actions"><button onClick={()=>setPreview(true)}><I.Play/> Preview</button><button className="primary" onClick={()=>void persist()}><I.Save/> Save Template</button></div></header>
  <section className="editor">
   <nav>{([['Model',I.Box],['Media',I.Image],['Text',I.Type],['Scene',I.Layers3]] as const).map(([name,Icon])=><button key={name} className={tool===name?'active':''} onClick={()=>setTool(name)}><Icon/><span>{name}</span></button>)}<button className="settings"><I.Settings/><span>Settings</span></button></nav>
   <aside className="left"><h2>{tool==='Model'?'Layers':tool}</h2><div className="layerList">{project.layers.map(layer=><LayerRow key={layer.id} layer={layer} selected={selectedId===layer.id} onSelect={()=>setSelected(layer.id)} onToggle={key=>update(d=>{const item=d.layers.find(x=>x.id===layer.id)!;item[key]=!item[key]})}/>)}</div><div className="modelCard"><div className="cardTitle"><h3>Model</h3><I.MoreHorizontal/></div><div className="asset"><div className="thumb"><Phone mini frame={0} project={project}/></div><div><b>{project.model?.fileName??'No model'}</b><small>{project.model?.fileSize?`${(project.model.fileSize/1024/1024).toFixed(1)} MB`:'Upload a GLB'}</small>{project.model?.assetId&&<span><I.CircleCheck/> Model ready</span>}</div></div>{project.model?.stats&&<div className="modelStats"><span>{project.model.stats.nodes} nodes</span><span>{project.model.stats.meshes} meshes</span><span>{project.model.stats.materials} materials</span><span>{project.model.stats.animations} animations</span><span>{project.model.stats.triangles.toLocaleString()} triangles</span></div>}<label className={`replace ${uploading?'disabled':''}`}><I.Upload/>{uploading?'Inspecting…':project.model?.assetId?'Replace Model':'Upload Model'}<input hidden type="file" accept=".glb,model/gltf-binary" disabled={uploading} onChange={e=>{void replaceModel(e.target.files?.[0]);e.target.value=''}}/></label>{uploadError&&<div className="modelError"><I.CircleAlert/>{uploadError}</div>}</div></aside>
   <div className={`workspace ${bgClass(project.background.preset)}`}><div className="canvasGlow"/>{isLayerActive(project,'phone',frame)&&project.model?.assetId?<SceneCanvas project={project} frame={frame} frameRequest={frameRequest} editable={selectedId==='phone'&&!selected.locked} mode={transformMode} onTransform={value=>update(d=>{if(d.model){d.model.position=value.position;d.model.rotation=value.rotation;d.model.scale=Math.max(.01,value.scale)}})} onCamera={(position,target)=>update(d=>{d.camera??={position:[0,.6,4],target:[0,0,0],fov:35,defaultPosition:[0,.6,4],defaultTarget:[0,0,0]};d.camera.position=position;d.camera.target=target})}/>:isLayerActive(project,'phone',frame)&&<div className={selectedId==='phone'?'selectionBox':''}><Phone frame={frame} project={project}/>{selectedId==='phone'&&[0,1,2,3].map(i=><i className={`handle h${i}`} key={i}/>)}</div>}{isLayerActive(project,'title',frame)&&<div className="canvasTitle">{project.layers.find(l=>l.id==='title')?.content}</div>}<div className="canvasControls"><button onClick={()=>setZoom(zoom-5)}><I.Minus/></button><b>{zoom}%</b><button onClick={()=>setZoom(zoom+5)}><I.Plus/></button><em/><button><I.Hand/></button><em/><button onClick={()=>setPlaying(!playing)}>{playing?<I.Pause/>:<I.Play/>}</button><button title="Frame model" onClick={()=>setFrameRequest(value=>value+1)}><I.Scan/></button></div></div>
   <Inspector project={project} layer={selected} update={update} mode={transformMode} setMode={setTransformMode}/>
  </section>
  <Timeline project={project} frame={frame} playing={playing} selectedId={selectedId} onFrame={setFrame} onPlay={setPlaying} onSelect={setSelected}/>
 </main>
}

function LayerRow({layer,selected,onSelect,onToggle}:{layer:ProjectLayer;selected:boolean;onSelect:()=>void;onToggle:(key:'visible'|'locked')=>void}){const Icon=icons[layer.type];return <div className={`layer ${selected?'selected':''}`} onClick={onSelect}><I.GripVertical className="grip"/><Icon/><span>{layer.name}</span><button aria-label={`${layer.visible?'Hide':'Show'} ${layer.name}`} onClick={e=>{e.stopPropagation();onToggle('visible')}}>{layer.visible?<I.Eye/>:<I.EyeOff/>}</button><button aria-label={`${layer.locked?'Unlock':'Lock'} ${layer.name}`} onClick={e=>{e.stopPropagation();onToggle('locked')}}>{layer.locked?<I.Lock/>:<I.Unlock/>}</button><I.MoreVertical/></div>}

function Inspector({project,layer,update,mode,setMode}:{project:TemplateProject;layer:ProjectLayer;update:(recipe:(draft:TemplateProject)=>void)=>void;mode:TransformMode;setMode:(mode:TransformMode)=>void}){const rotation=project.model?.rotation??[0,0,0];return <aside className="inspector"><div className="inspectorHead"><h2>{layer.name}</h2><I.MoreHorizontal/></div>
 <Panel title="Direct Controls"><div className="transformModes"><button className={mode==='translate'?'on':''} onClick={()=>setMode('translate')}><I.Move3d/> Move</button><button className={mode==='rotate'?'on':''} onClick={()=>setMode('rotate')}><I.Rotate3d/> Rotate</button><button className={mode==='scale'?'on':''} onClick={()=>setMode('scale')}><I.Maximize2/> Scale</button></div></Panel>
 <Panel title="Transform"><label>Position</label><div className="triple">{['X','Y','Z'].map((axis,i)=><Field key={axis} label={axis} value={project.model?.position[i]??0} onChange={value=>update(d=>{if(d.model)d.model.position[i]=value})}/>)}</div><label>Rotation</label><div className="triple">{['X','Y','Z'].map((axis,i)=><Field key={axis} label={axis} value={rotation[i]} suffix="°" onChange={value=>update(d=>{if(d.model)d.model.rotation[i]=value})}/>)}</div><label>Scale</label><div className="triple"><Field label="S" value={project.model?.scale??1} onChange={value=>update(d=>{if(d.model)d.model.scale=Math.max(.01,value)})}/></div></Panel>
 <Panel title="Animation"><Select label="Preset" value={project.animation.preset} options={['Flip Reveal','Float and Focus','Side Slide']} onChange={value=>update(d=>{d.animation.preset=value as TemplateProject['animation']['preset']})}/><Select label="Direction" value={project.animation.direction} options={['Left','Right','Up','Down']} onChange={value=>update(d=>{d.animation.direction=value as TemplateProject['animation']['direction']})}/><div className="row"><label>Duration</label><div className="input">{(project.animation.durationInFrames/project.canvas.fps).toFixed(1)} <span>s</span></div></div><div className="row"><label>Intensity</label><input type="range" value={project.animation.intensity} onChange={e=>update(d=>{d.animation.intensity=Number(e.target.value)})}/><div className="smallInput">{project.animation.intensity} %</div></div></Panel>
 <Panel title="Screen"><Select label="Material" value={project.screen?.materialName??'Not mapped'} options={['17ProMax_Screen','Display_Glass']} onChange={value=>update(d=>{if(d.screen)d.screen.materialName=value})}/><div className="row"><label>Fit Mode</label><div className="segments">{(['fill','fit','stretch'] as const).map(value=><button key={value} className={project.screen?.fit===value?'on':''} onClick={()=>update(d=>{if(d.screen)d.screen.fit=value})}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div></div></Panel>
 <Panel title="Normalization"><Select label="Front" value={project.model?.frontAxis??'+Z'} options={['+Z','-Z','+X','-X','+Y','-Y']} onChange={value=>update(d=>{if(d.model)d.model.frontAxis=value as NonNullable<TemplateProject['model']>['frontAxis']})}/><label>Animation Pivot</label><div className="triple">{['X','Y','Z'].map((axis,i)=><Field key={axis} label={axis} value={project.model?.pivot[i]??0} onChange={value=>update(d=>{if(d.model)d.model.pivot[i]=value})}/>)}</div><div className="normalizationActions"><button onClick={()=>update(d=>{if(d.model)d.model.position[1]=0})}><I.ArrowDownToLine/> Place on ground</button><button onClick={()=>update(d=>{if(!d.model)return;d.model.position=[0,0,0];d.model.rotation=[0,0,0];d.model.scale=1;d.model.pivot=[0,0,0]})}><I.RefreshCcw/> Reset transform</button><button onClick={()=>update(d=>{if(!d.model)return;d.model.defaultTransform={position:[...d.model.position],rotation:[...d.model.rotation],scale:d.model.scale,pivot:[...d.model.pivot],frontAxis:d.model.frontAxis};if(d.camera){d.camera.defaultPosition=[...d.camera.position];d.camera.defaultTarget=[...d.camera.target]}})}><I.BookmarkCheck/> Save default view</button><button disabled={!project.model?.defaultTransform} onClick={()=>update(d=>{const saved=d.model?.defaultTransform;if(!d.model||!saved)return;d.model.position=[...saved.position];d.model.rotation=[...saved.rotation];d.model.scale=saved.scale;d.model.pivot=[...saved.pivot];d.model.frontAxis=saved.frontAxis;if(d.camera){d.camera.position=[...d.camera.defaultPosition];d.camera.target=[...d.camera.defaultTarget]}})}><I.History/> Restore default</button></div></Panel>
 <Panel title="Appearance" collapsed><Select label="Background" value={project.background.preset} options={['Soft Blue','Lilac Glow','Midnight Studio']} onChange={value=>update(d=>{d.background.preset=value as TemplateProject['background']['preset']})}/></Panel>
 {project.model?.stats&&<MaterialBrowser names={project.model.stats.materialNames}/>}</aside>}

function Phone({frame,project,mini=false}:{frame:number;project:TemplateProject;mini?:boolean}){const rotation=project.model?.rotation??[0,0,0],progress=easeOutCubic(frame/project.animation.durationInFrames),direction=project.animation.direction==='Right'?1:-1,reveal=project.animation.preset==='Flip Reveal'?direction*(1-progress)*75*project.animation.intensity/100:0,rise=project.animation.preset==='Float and Focus'?(1-progress)*60:(1-progress)*25;return <div className={`phone ${mini?'mini':''}`} style={{transform:`perspective(900px) rotateX(${rotation[0]}deg) rotateY(${rotation[1]+reveal}deg) rotateZ(${rotation[2]-7}deg) translateY(${rise}px) scale(${project.model?.scale??1})`}}><div className="speaker"/><div className="screen"><div className="status"><b>9:41</b><span>● ◒</span></div><div className="hello"><span>Hello, Alex</span><i/></div><small>Welcome back</small><div className="balance"><small>Total balance</small><strong>$24,850<sup>.50</sup></strong><mark>▲ 8.5% vs last month</mark></div><div className="chart"><b>Overview</b><svg viewBox="0 0 200 85"><path d="M0 70 C20 70 18 48 35 54 S48 31 65 45 S80 60 96 31 S115 21 126 43 S145 51 151 24 S168 37 177 8 S190 12 200 0"/></svg></div><b className="cat">Top Categories</b>{['Shopping','Travel','Food & Drinks','Entertainment'].map((name,i)=><div className="category" key={name}><i style={{background:['#7c4dff','#1597ff','#20c997','#ef476f'][i]}}/><span>{name}</span><b>${[6420,4210,3130,2450][i]}.40</b></div>)}<div className="dock"><I.Home/><I.CreditCard/><I.BarChart3/><I.User/></div></div></div>}

function Timeline({project,frame,playing,selectedId,onFrame,onPlay,onSelect}:{project:TemplateProject;frame:number;playing:boolean;selectedId:string;onFrame:(frame:number)=>void;onPlay:(playing:boolean)=>void;onSelect:(id:string)=>void}){const duration=project.canvas.durationInFrames,seconds=duration/project.canvas.fps,ticks=useMemo(()=>Array.from({length:Math.ceil(seconds/2)},(_,i)=>i*2),[seconds]);return <footer><div className="timeHead"><button onClick={()=>onPlay(!playing)}>{playing?<I.Pause/>:<I.Play/>}</button><b>{formatTimecode(frame,project.canvas.fps)}</b><span>/ {formatTimecode(duration,project.canvas.fps)}</span><div className="timelineTools"><button><I.Minus/></button><input aria-label="Timeline zoom" type="range"/><button><I.Plus/></button><I.Scan/></div></div><div className="tracks"><div className="ruler">{ticks.map(second=><span key={second} style={{left:`${second/seconds*100}%`}}>00:{String(second).padStart(2,'0')}</span>)}</div><div className="playhead" style={{left:`calc(295px + ${frame/duration} * (100% - 315px))`}}><i/></div>{project.layers.filter(l=>l.type!=='background').map(layer=>{const Icon=icons[layer.type];return <div className={`track ${selectedId===layer.id?'sel':''}`} key={layer.id} onClick={()=>onSelect(layer.id)}><div className="trackLabel"><Icon/><span>{layer.name}</span>{layer.locked?<I.Lock/>:<I.Unlock/>}</div><div className="clipArea" onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();onFrame((e.clientX-rect.left)/rect.width*duration)}}><div className="clip" style={{left:`${layer.startFrame/duration*100}%`,width:`${layer.durationInFrames/duration*100}%`,background:`linear-gradient(90deg,${layer.color}55,${layer.color}aa)`}}><span>{layer.type==='device'?`${project.animation.preset} (${project.animation.direction})`:layer.type==='screen-media'?'Dashboard.mp4':layer.type==='text'?layer.content:'Camera Move'}</span></div></div></div>})}</div></footer>}

function Preview({project,frame,playing,onFrame,onPlay,onClose}:{project:TemplateProject;frame:number;playing:boolean;onFrame:(frame:number)=>void;onPlay:(playing:boolean)=>void;onClose:()=>void}){return <div className={`preview ${bgClass(project.background.preset)}`}><button className="backPreview" onClick={onClose}><I.ChevronLeft/> Back to editor</button>{project.model?.assetId?<div className="previewModel"><SceneCanvas project={project} frame={frame}/></div>:<Phone frame={frame} project={project}/>}<div className="previewCopy"><span>INTRODUCING</span><h1>{project.layers.find(l=>l.id==='title')?.content}</h1><p>Designed to turn product screens into polished launch stories.</p></div><div className="previewBar"><button onClick={()=>onPlay(!playing)}>{playing?<I.Pause/>:<I.Play/>}</button><input type="range" min="0" max={project.canvas.durationInFrames-1} value={frame} onChange={e=>onFrame(Number(e.target.value))}/><b>{formatTimecode(frame,project.canvas.fps)} / {formatTimecode(project.canvas.durationInFrames,project.canvas.fps)}</b></div></div>}
function isLayerActive(project:TemplateProject,id:string,frame:number){const layer=project.layers.find(item=>item.id===id);return Boolean(layer?.visible&&frame>=layer.startFrame&&frame<layer.startFrame+layer.durationInFrames)}
function Panel({title,children,collapsed=false}:{title:string;children:ReactNode;collapsed?:boolean}){const [open,setOpen]=useState(!collapsed);return <section className="panel"><button className="panelTitle" onClick={()=>setOpen(!open)}><I.ChevronDown className={!open?'closed':''}/><b>{title}</b><I.ChevronUp/></button>{open&&<div className="panelBody">{children}</div>}</section>}
function Field({label,value,suffix='',onChange}:{label:string;value:number;suffix?:string;onChange:(value:number)=>void}){const [text,setText]=useState(`${value}${suffix}`);return <div className="field"><span>{label}</span><input value={text} onFocus={()=>setText(String(value))} onChange={e=>setText(e.target.value)} onBlur={()=>{const parsed=Number.parseFloat(text);if(Number.isFinite(parsed))onChange(parsed);setText(`${Number.isFinite(parsed)?parsed:value}${suffix}`)}}/></div>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <div className="row"><label>{label}</label><div className="select"><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select><I.ChevronDown/></div></div>}
function MaterialBrowser({names}:{names:string[]}){const [query,setQuery]=useState(''),filtered=names.filter(name=>name.toLowerCase().includes(query.toLowerCase()));return <Panel title={`Materials (${names.length})`} collapsed><div className="materialSearch"><I.Search/><input placeholder="Search materials" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="materialList">{filtered.map(name=><button key={name}><I.Circle/><span>{name}</span></button>)}{!filtered.length&&<small>No matching materials</small>}</div></Panel>}
